from Tkinter import *

def fun():
    root.destroy()
def splashscreen():
    global root
    root=Tk()
    root.geometry("1600x800+0+0")
    root.configure(bg='white')
    Label(root,text="Banking System",font="Aerial 30 ",bd=5,bg='white').grid(row=1,column=1,columnspan=3)
    Label(root,text="Name",font="Aerial 20 bold",bg='white').grid(row=2,column=1,sticky=E)
    Label(root,text=":",font="Aerial 20 bold",bg='white').grid(row=2,column=2)
    Label(root,text="Utkarsh Singh",font="Aerial 20 bold",bg='white').grid(row=2,column=3,sticky=W)
    Label(root,text="Enrollment No.",font="Aerial 20 bold",bg='white').grid(row=3,column=1,sticky=E)
    Label(root,text=":",font="Aerial 20 bold",bg='white').grid(row=3,column=2)
    Label(root,text="161B257",font="Aerial 20 bold",bg='white').grid(row=3,column=3,sticky=W)
    Label(root,text="Batch",font="Aerial 20 bold",bg='white').grid(row=4,column=1,sticky=E)
    Label(root,text=":",font="Aerial 20 bold",bg='white').grid(row=4,column=2)
    Label(root,text="B-9(BZ)",font="Aerial 20 bold",bg='white').grid(row=4,column=3,sticky=W)
    Label(root,text="Branch",font="Aerial 20 bold",bg='white').grid(row=5,column=1,sticky=E)
    Label(root,text=":",font="Aerial 20 bold",bg='white').grid(row=5,column=2)
    Label(root,text="Computer Science",font="Aerial 20 bold",bg='white').grid(row=5,column=3,sticky=W)
    Label(root,text="& Engineering",font="Aerial 20 bold",bg='white').grid(row=6,column=3,sticky=W)
    Label(root,text="Course",font="Aerial 20 bold",bg='white').grid(row=7,column=1,sticky=E)
    Label(root,text=":",font="Aerial 20 bold",bg='white').grid(row=7,column=2)
    Label(root,text="B. Tech (IInd Year)",font="Aerial 20 bold",bg='white').grid(row=7,column=3,sticky=W)
    Label(root,text="E. Mail id",font="Aerial 20 bold",bg='white').grid(row=8,column=1,sticky=E)
    Label(root,text=":",font="Aerial 20 bold",bg='white').grid(row=8,column=2)
    Label(root,text="utkarshsingh5298291@gmail.com",font="Aerial 20 bold",bg='white').grid(row=8,column=3,sticky=W)
    Label(root,text="Submitted To",font="Aerial 20 bold",bg='white').grid(row=9,column=1,sticky=E)
    Label(root,text=":",font="Aerial 20 bold",bg='white').grid(row=9,column=2)
    Label(root,text="Dr. Mahesh Kumar",font="Aerial 20 bold",bg='white').grid(row=9,column=3,sticky=W)
    root.after(6000,fun)
    root.mainloop()
